
---
homebrew_installed_packages:
  - autojump
  - elixir
  - fd
  - fzf
  - git
  - go
  - htop
  - mercurial
  - rbenv
  - ripgrep
  - scala
  - sbt
  - shellcheck
  - tree
  - unrar
  - wget
  - yamllint

homebrew_taps:
  - homebrew/cask
  - homebrew/core

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - dropbox
  - emacs
  - firefox
  - fly
  - gpg-suite-no-mail
  - intellij-idea-ce
  - iterm2
  - notion
  - slate
  - spotify
  - vagrant
  - visual-studio-code
  - vlc

zsh_aliases:
  - { alias: 'ag', action: 'rg' }
  - { alias: 'find', action: 'fd' }
zsh_antigen_theme: muse
zsh_antigen_bundles_extras:
  - { name: git, command: git }
