
---
homebrew_installed_packages:
  - autojump
  - elixir
  - fzf
  - git
  - go
  - htop
  - mercurial
  - ripgrep
  - shellcheck
  - tree
  - unrar
  - wget

homebrew_taps:
  - homebrew/cask
  - homebrew/core

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - dropbox
  - emacs
  - firefox
  - iterm2
  - slate
  - spotify
  - vagrant
  - vlc

zsh_aliases:
  - { alias: 'ag', action: 'rg' }
zsh_antigen_theme: muse
zsh_antigen_bundles_extras:
  - { name: git, command: git }
