
---
homebrew_installed_packages:
  - autojump
  - fzf
  - git
  - go
  - htop
  - mercurial
  - ripgrep
  - tree
  - unrar
  - wget

homebrew_taps:
  - homebrew/cask
  - homebrew/core

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - emacs
  - firefox
  - google-chrome
  - iterm2
  - slack
  - slate
  - vagrant
