
---
homebrew_installed_packages:
  - autojump
  - elixir
  - fzf
  - git
  - go
  - htop
  - mercurial
  - ripgrep
  - shellcheck
  - tree
  - unrar
  - wget

homebrew_taps:
  - homebrew/cask
  - homebrew/core

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - android-studio
  - docker
  - dropbox
  - emacs
  - firefox
  - google-chrome
  - iterm2
  - slack
  - slate
  - spotify
  - vagrant
  - vlc

zsh_aliases:
  - { alias: 'ag', action: 'rg' }
zsh_antigen_theme: muse
