---

- hosts: localhost
  connection: local
  vars_files:
    - default.config.yml
  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
  tasks:
    - include_tasks: tasks/emacs.yml
    - include_tasks: tasks/dotfiles.yml
