---

- name: Create Project directory
  file:
    path: "{{ lookup('env','HOME') }}/Projects"
    state: directory

- name: Check out dotfiles repo
  git:
    repo: 'git@github.com:KushalP/dotfiles.git'
    dest: "{{ lookup('env','HOME') }}/Projects/dotfiles"
    update: no
  register: dotfiles_clone

- name: Update symlinks
  command: 'make'
  args:
    chdir: "{{ lookup('env','HOME') }}/Projects/dotfiles"
  when: dotfiles_clone.changed
